### PR TITLE
'UpdateBuilder.onDeleteUnrelate()' for managing relationships #62

### PR DESCRIPTION
**Pull request by atomashpolskiy**

### CODE REVIEW

**Comment by atomashpolskiy** [comment]
You probably should not merge com.nhl.link.rest.it.fixture.resource.E8Resource and E12Resource updates, because onDeleteUnrelate causes DB constraints validation failure in them.

**Comment by andrus** [comment]
Is it possible to update the pull request to exclude things that should not go there?

**Comment by atomashpolskiy** [comment]
Should be OK now.

**Comment by atomashpolskiy** [comment]
See #75

**Pull request closed without merging**
