### PR TITLE
Store information about the target entity in LrRelationship #185

### PR DESCRIPTION
**Pull request by atomashpolskiy**
@andrus , please review; this includes the fix for #184

### CODE REVIEW

**Comment by andrus** [comment]
@atomashpolskiy : all looks good except PojoEntityCompiler is not using lazy LazyLrEntity and does eager compilation.

**Comment by atomashpolskiy** [comment]
@andrus , you are right, this is because in contrast to the Cayenne compiler the Pojo compiler can't tell if it's a pojo entity without compiling the class first. And the current design implies that each compiler should immediately respond to the LrDataMap either with null or a [lazy] entity. We could work around this problem by always calling the Pojo compiler last (after everybody else returned null), but LrDataMap does not know anything about the nature of the compilers... Let's discuss offline maybe?

**Comment by atomashpolskiy** [comment]
@andrus , updated the PR

**Comment by andrus** [comment]
applied. I did a rebase, so commits IDs don't match. But they are really unchanged.

**Pull request closed without merging**
