### PR TITLE
Sencha adapter "filter" key can't use "id" property #202

### PR DESCRIPTION
**Pull request by atomashpolskiy**
@andrus , here's a simplistic fix for this issue. If you wanted something more sophisticated -- like a separate ExpressionPostProcessorService for instance to avoid duplicating code -- let me know. Also what about JSON value converters -- should they be used as well?

### CODE REVIEW

**Comment by andrus** [comment]
> If you wanted something more sophisticated -- like a separate ExpressionPostProcessorService for instance to avoid duplicating code -- let me know. 

yeah, if you have time this or next week, would be great to refactor this functionality into some reusable code. Otherwise it will be hard to trace all the special cases. If you don't, we can commit the fix now, and open a separate task to improve it.

> Also what about JSON value converters -- should they be used as well?

I'd say yes. I may not remember all the details about Sencha filter client-side specifics, but the general approach is that Sencha experience should be based on the same foundation as default protocol.

**Comment by atomashpolskiy** [comment]
@andrus , check it out
A few notes:
1) Now there are 2 instances of ExpressionPostProcessor being created in SenchaFilterProcessor and CayenneExpProcessor, and each of these instances maintains its own cache of post processors; if you'd like we might put this into DI, I guess
2) Note that `ExpressionPostProcessor` is now making some assumptions about Java types of expression parameters. I'm not sure how to externalize this logic from it

**Comment by andrus** [comment]
1. While the build succeeded on Travis, on my machine I am getting a unit test failure:
```  
GET_CayenneExpIT.test_CayenneExp_MatchById:37 
expected:<{"data":[{"id":2}[],"total":1]}> 
but was:<{"data":[{"id":2}[,{"id":3}],"total":2]}>
```

2.
> Now there are 2 instances of ExpressionPostProcessor being created in SenchaFilterProcessor and CayenneExpProcessor, and each of these instances maintains its own cache of post processors; if you'd like we might put this into DI, I guess.

+1

**Comment by atomashpolskiy** [comment]
@andrus , I can't see this test in master: [https://github.com/nhl/link-rest/blob/master/link-rest/src/test/java/com/nhl/link/rest/it/noadapter/GET_CayenneExpIT.java](https://github.com/nhl/link-rest/blob/master/link-rest/src/test/java/com/nhl/link/rest/it/noadapter/GET_CayenneExpIT.java)

**Comment by andrus** [comment]
My bad. I had a local test on my copy. I just committed the changes. Feel free to amend this further (moving that object under DI).

**Pull request merged**
