### PR TITLE
#287 Added 'queryParam' constraint.

### PR DESCRIPTION
**Pull request by vyarmolovich**

### CODE REVIEW

**Comment by andrus** [comment]
@vyarmolovich : Looks good overall. One issue: the new API doesn't handle the case when a constraint is in use, but no parameters are specified explicitly. E.g. the following should allow unrestricted parameters, but in fact will forbid any of them. So let's create a test for it and address in the algorithm.

```java
LinkRest.service(config)
   .select(E4.class)
   .constraint(Constraint.idAndAttributes(E4.class))
   .uri(uriInfo)
   .get();
```

**Comment by vyarmolovich** [comment]
@andrus 
I have fixed the issue. But I have question regarding constraint method names.
May be it will be better if we introduce an additional method to handle three of them Id, Attributes, QueryParams?   
And present idAndAttributes will process id and all attributes but with no query parameters.

```
LinkRest.service(config)
   .select(E4.class)
   .constraint(Constraint.idAndAttributesAndQueryParams(E4.class))
   .uri(uriInfo)
   .get();
```

**Comment by andrus** [comment]
The method naming will become too long unfortunately.. Also there are other methods - `idOnly` and `excludeAll`, which would have to be changed too ... So for now I suggest we keep the old  names for the factory methods and allow all keys by default across all 3 factory methods. While this is not ideal, it is backwards compatible and people are used to all keys being allowed implicitly.

**Comment by andrus** [comment]
I think the way this should work (irregardless of the builder method used) is similar to how includes are currently handled: if you don't specify explicit parameters, then all parameters should be allowed implicitly. Once you specify at least one parameter, all implicit parameters should be suppressed, and only explicitly set ones should be allowed. I think this last piece of behavior is still missing.

**Comment by vyarmolovich** [comment]
Yes, I got it. From backwards compatible it looks reasonable. In that case I have to change `idOnly` and `excludeAll` methods as well and make additional refactoring regarding implicit parameters.

**Comment by vyarmolovich** [comment]
I have done with it. Now if we don't specify any `queryParam` constraints, all parameters are supported.

**Comment by andrus** [comment]
Does `ConstraintBuilder.excludeAllQueryParams(..)` operate correctly? It clears 'queryParams' map. But a cleared map is equivalent to "all params". Do we need a different mechanism to store state between all implicit, all or some explicit, or none?

**Comment by vyarmolovich** [comment]
Yes, `ConstraintBuilder.excludeAllQueryParams(..)` does not operate correctly now.  I think it can be removed for the moment. Actually, from swagger integration perspective  there is not any cases to use this method. 
More over, there is one more case regarding `queryParams` I am working on. It is when we use `queryParams` to send compound id:
```
        Response response2 = target("/multi-id/byid")
                .queryParam("age", 18).queryParam("name", "John")
                .queryParam("exclude", "description").request().get();
```

**Comment by vyarmolovich** [comment]
Nevertheless, I am worried about "all implicit".
If we provided with such implementation, it would motivate end-user do not configure `queryParams` in yaml rather use them implicitly. And as a result, the generated api docs and UI would not be consistent.

**Comment by vyarmolovich** [comment]
Closed. Query parameters will be processed explicit without any constraints and uriInfo.

**Pull request closed without merging**
