### PR TITLE
LR metadata

### PR DESCRIPTION
**Pull request by atomashpolskiy**
Still need to figure out how to determine types of links.

*Example output for E2 resource/E2 entity:*

```javascript
{
  "success": true,
  "entity": {
    "name": "E2",
    "properties": [
      {
        "name": "address",
        "type": "string"
      },
      {
        "name": "e3s",
        "type": "E3",
        "relationship": true,
        "collection": true
      },
      {
        "name": "name",
        "type": "string"
      }
    ]
  },
  "links": [
    {
      "href": "http://localhost:9998/e2",
      "type": "collection",
      "operations": [
        {
          "method": "GET"
        }
      ]
    },
    {
      "href": "http://localhost:9998/e2/metadata",
      "type": "metadata",
      "operations": [
        {
          "method": "GET"
        }
      ]
    },
    {
      "href": "http://localhost:9998/e2/{id}",
      "type": "item",
      "operations": [
        {
          "method": "DELETE"
        },
        {
          "method": "GET"
        }
      ]
    }
  ]
}

### CODE REVIEW

**Comment by andrus** [comment]
Great! One suggestion - I don't think we need to wrap metadata in our collection document. I.e. what's currently is under the "data" key should be at the top level of response JSON.

**Comment by atomashpolskiy** [comment]
I was thinking that it's a common approach for LR, because this format is dictated by *com.nhl.link.rest.provider.BaseResponseWriter*. Then I guess we should stretch writer hierarchy by pulling "real" base-writer out of BaseResponseWriter and rename the former, because all of it's code is needed for new MetadataResponseWriter (except for message format).

**Comment by andrus** [comment]
actually 'writeData' subclass method can be implemented to write extra keys at the top level. It does not require to go an extra depth level.

**Comment by atomashpolskiy** [comment]
Not sure if I understand your point, could you be more specific please?

**Comment by andrus** [comment]
BaseResponseWriter creates a structure like this:

    { 
     "success":true, 
     "message":"...",
    /* custom json generated by 'writeData' method*/
    }

As you see it does not force you to use a "data" key.

**Comment by atomashpolskiy** [comment]
Ah, you mean "success" attribute is OK at top-level? I misunderstood your initial comment:
> I don't think we need to wrap metadata in our collection document. I.e. what's currently is under the "data" key should be at the top level of response JSON.

**Comment by andrus** [comment]
I am 50/50 on "success" key. but I guess it is fine.

**Comment by atomashpolskiy** [comment]
Done. Changed example in the initial message

**Comment by andrus** [comment]
So the remaining items:

1. URL escaping: Do not escape the URLs
2. Multiple methods for the same link. It is not clear from the example whether we already combine multiple resource methods that have the same URL into a single "link"? (of course we should). 
3. Link type. To determine the type of endpoints we may use the following annotation:

     @LrMethod(LinkType.<TYPE>)

     // where LinkType is an enum of COLLECTION, ITEM, METADATA, UNDEFINED

If multiple methods are present for a given "link", it should be enough  to annotate any one of them with @LrMethod, and we'll extend it to others automatically. If multiple methods for the same URL contain conflicting @LrMethod annotations, we should detect and throw an exception.

**Comment by atomashpolskiy** [comment]
2 is already done, of course. It's LrResource's list of operations actually.

On URL escaping, I'm not sure that it would be simple, it's jackson after all.

**Comment by atomashpolskiy** [comment]
3 done, updated initial comment.

**Comment by andrus** [comment]
Awesome. Let's maybe take a look at encoding also. Hopefully Jackson allows this strategy to be changed

**Comment by atomashpolskiy** [comment]
Actually that was not Jackson escaping slashes, it was my JSON formatter. Sorry for that :)

**Comment by atomashpolskiy** [comment]
Added tests and introduced new service for resource metadata.

**Comment by andrus** [comment]
Just applied with a minor cleanup (annotated new classes/methods with "@since 1.18", and resolved a few generics warnings). Thanks!!

**Pull request merged**
